import { CompanyData } from "@/lib/mockData";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Copy, Download, AlertTriangle } from "lucide-react";
import { toast } from "sonner";

export const MemoTab = ({ c }: { c: CompanyData }) => {
  const m = c.memo;
  const range = m.bull - m.bear;
  const basePct = ((m.base - m.bear) / range) * 100;

  const text = `EQUIMIND RESEARCH — ${c.ticker} (${c.name})

RATING: ${c.rating}    INTRINSIC: $${c.intrinsicValue}    UPSIDE: ${c.upside}%

1. BUSINESS SUMMARY
${m.summary}

2. FINANCIAL PERFORMANCE
${m.performance}

3. VALUATION RANGE
Bear: $${m.bear} | Base: $${m.base} | Bull: $${m.bull}

4. KEY RISKS
${m.risks.map((r) => `- ${r}`).join("\n")}

5. INVESTMENT THESIS
${m.thesis}

6. BEAR CASE
${m.bearCase}
`;

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-end gap-2">
        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            navigator.clipboard.writeText(text);
            toast.success("Memo copied to clipboard");
          }}
        >
          <Copy className="h-4 w-4" /> Copy memo
        </Button>
        <Button variant="hero" size="sm" onClick={() => toast.info("PDF export coming in Pro")}>
          <Download className="h-4 w-4" /> Download PDF
        </Button>
      </div>

      <Card className="border-border bg-card p-8 shadow-card">
        <div className="border-b border-border pb-6">
          <div className="text-[11px] font-semibold uppercase tracking-[0.2em] text-accent">EquiMind Research Note</div>
          <h2 className="mt-2 font-display text-2xl font-semibold">{c.name} ({c.ticker})</h2>
          <div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
            <span>{c.sector}</span><span>·</span>
            <span>{c.industry}</span><span>·</span>
            <span className="font-mono-num">Mkt Cap {c.marketCap}</span>
          </div>
        </div>

        <Section n="1" title="Business Summary">
          <p>{m.summary}</p>
        </Section>

        <Section n="2" title="Financial Performance">
          <p>{m.performance}</p>
        </Section>

        <Section n="3" title="Valuation Range">
          <div className="rounded-lg border border-border bg-surface-muted p-5">
            <div className="grid grid-cols-3 gap-4">
              <RangeBox label="Bear" value={m.bear} tone="bear" />
              <RangeBox label="Base" value={m.base} tone="accent" highlight />
              <RangeBox label="Bull" value={m.bull} tone="bull" />
            </div>
            <div className="relative mt-6 h-2 rounded-full bg-gradient-to-r from-bear via-neutral to-bull">
              <div
                className="absolute -top-1 h-4 w-4 -translate-x-1/2 rounded-full border-4 border-card bg-foreground shadow"
                style={{ left: `${basePct}%` }}
              />
            </div>
            <div className="mt-2 flex justify-between font-mono-num text-[11px] text-muted-foreground">
              <span>${m.bear}</span><span>${m.bull}</span>
            </div>
          </div>
        </Section>

        <Section n="4" title="Key Risks">
          <ul className="space-y-2">
            {m.risks.map((r) => (
              <li key={r} className="flex items-start gap-2.5 text-sm">
                <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-neutral" />
                <span>{r}</span>
              </li>
            ))}
          </ul>
        </Section>

        <Section n="5" title="Investment Thesis">
          <p>{m.thesis}</p>
        </Section>

        <Section n="6" title="Bear Case">
          <p>{m.bearCase}</p>
        </Section>

        <div className="mt-8 flex items-center justify-between border-t border-border pt-5 text-[11px] text-muted-foreground">
          <span>Generated by EquiMind · {new Date().toLocaleDateString()}</span>
          <Badge variant="outline" className="border-border">For research use only</Badge>
        </div>
      </Card>
    </div>
  );
};

const Section = ({ n, title, children }: { n: string; title: string; children: React.ReactNode }) => (
  <section className="mt-6 border-b border-border pb-6 last:border-b-0">
    <div className="mb-2 flex items-baseline gap-3">
      <span className="font-mono-num text-xs font-semibold text-accent">{n}</span>
      <h3 className="font-display text-base font-semibold">{title}</h3>
    </div>
    <div className="text-sm leading-relaxed text-foreground/85">{children}</div>
  </section>
);

const RangeBox = ({ label, value, tone, highlight }: { label: string; value: number; tone: "bear" | "bull" | "accent"; highlight?: boolean }) => {
  const color = tone === "bear" ? "text-bear" : tone === "bull" ? "text-bull" : "text-accent";
  return (
    <div className={`rounded-md border p-4 text-center ${highlight ? "border-accent bg-accent-soft/40" : "border-border bg-card"}`}>
      <div className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className={`mt-1 font-mono-num text-2xl font-semibold ${color}`}>${value}</div>
    </div>
  );
};
