RISK_FREE_RATE = 0.045
BENCHMARK_TICKER = "^GSPC"
BETA_LOOKBACK_YEARS = 2
BETA_FREQUENCY = "W"
BETA_USE_ADJUSTED = True
SHARPE_LOOKBACK_YEARS = 2
VAR_CONFIDENCE_LEVEL = 0.95
DRAWDOWN_LOOKBACK_YEARS = 5
MIN_PRICE_HISTORY_YEARS = 1
ZSCORE_SAFE = 2.99
ZSCORE_DISTRESS = 1.81
ZSCORE_EXCLUDED_SECTORS = {"Financials", "Real Estate"}

AV_API_KEYS = [
    "7S6SYRX0FO4Y629W",
    "4A92Z90SXGQ1VKWY",
    "1UULEYN0S6V9A0ZP",
    "PU3U6SOA0QCW2B0E",
    "HY18XN62PCFE1BCL",
]
